# This workflows will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Upload Python Package

on: [push]

jobs:
  deploy:
    defaults:
      run:
        working-directory: ./cvplay   # job level working directory
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          python_version:  '3.6.0'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --user setuptools wheel twine
      - name: Build and publish
        env:
          TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
        run: |
          python setup.py sdist bdist_wheel
          twine upload testpypi dist/* 
